version: "2.1"
services:
    mongo:
      image: "mongo:3"
      ports:
        - "27017:27017"
      volumes:
        - ./db:/data/db
#    redis:
#      image: redis
#      ports:
#        - "6380:6379"
    app1:
      build:
        context: ./build/app1
        args:
          port: 10001
      links:
        - mongo
        - app2
      ports:
        - "8080:10001"
#      volumes:
#        - ./build/app1:/root/app
    app2:
      build:
        context: ./build/app2
        args:
          port: 10002
      links:
        - mongo
      expose:
        - 10002
#      volumes:
#        - ./build/app2:/root/app
#      ports:
#        - "8081:10002"