version: "2.1"
services:
    mongo:
      image: "mongo:3"
      ports:
        - "27017:27017"
      volumes:
        - ./dumps:/root/backup
    redis:
      image: redis
      ports:
        - "6380:6379"
    app1:
      build:
        context: ./build/app1
      links:
        - mongo
        - redis
      environment:
        PORT: 10001
    app2:
      build:
        context: ./build/app1
      links:
        - mongo
        - redis
      environment:
        PORT: 10002
#networks:
#  public:
#  backend:
#    - driver: overlay