swagger: '2.0'
info:
  version: "0.0.1"
  title: Demo swagger app - stage 2 - app 1
  description: app 1 is designed for auth/registration procedures
host: 127.0.0.1:10010
basePath: /api
schemes:
  - http
#  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    x-swagger-router-controller: auth
    get:
      description: Returns all incoming requests in descending order
      operationId: register
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/RegisterRequest"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /add:
     x-swagger-router-controller: test_api
     post:
      description: Receives array of 2 points and calculates distance between them
      operationId: addPoint
      parameters:
        - name: points
          in: body
          description: JSON object with array of 2 geo points
          required: true
          schema: 
            $ref: "#/definitions/PointsRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AddPointsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  RegisterRequest:
    type: object
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string